Main svc
PetrVladimirovich/java-explore-with-me pull request #5
Opened 2023-04-26 17:24 UTC by PetrVladimirovich

2023-04-27 06:24 UTC, krylov-sergey-sergeevich requested changes
Привет, очень неплохо, давай чутка обсудим/поправим и будет зачет

2023-04-27 06:24 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/ewm/controller/pub/EventPublicController.java
> +    private final DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Я бы вынес в DataUtils

2023-04-27 06:24 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/ewm/dto/ApiErrorDto.java
> +    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
Вынес бы в DateUtils

2023-04-27 06:24 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/ewm/dto/ApiErrorDto.java
> +        this.timestamp = LocalDateTime.now();
Instant.now() - рекомендую создать отдельный класс DateUtils и будем создавать объекты времени через него, это позволит унифицировать способ получения времени и если будут правки делать их в 1 месте.

2023-04-27 06:24 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/ewm/dto/ParticipationRequestDto.java
> +    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS")
DateUtils

2023-04-27 06:24 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/ewm/dto/event/EventFullDto.java
> +    private static final String TIME_FORMAT = "yyyy-MM-dd HH:mm:ss";
Зачем тут это поле?

2023-04-27 06:24 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/ewm/dto/event/EventShortDto.java
> +    private static final String TIME_FORMAT = "yyyy-MM-dd HH:mm:ss";
Дублируем это

2023-04-27 06:24 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/ewm/service/impl/CompilationServiceImpl.java
> +                .orElseThrow(() -> new ObjectNotFoundException(String.format("Compilation with id=%d was not found", compId)));
Рекомендую для каждого типа объектов создавать свой тип исключений чтобы не дублировать текста
т.е
CompilationNotFound(id)

2023-04-27 06:24 UTC, krylov-sergey-sergeevich commented on pom.xml
> +		<version>2.7.2</version>
Почему понизил?

2023-04-30 12:08 UTC, PetrVladimirovich commented on pom.xml
> +		<version>2.7.2</version>
у меня какой-то трабл случился, теперь несколько Life cicle в maven автоматом выбирал решать проблему видимо поменяло

2023-04-30 12:28 UTC, PetrVladimirovich commented on main-service/src/main/java/ru/practicum/ewm/controller/pub/EventPublicController.java
> +    private final DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Привет, у тебя бывало такое что надоело однотипные задачи делать? У меня вот щас нет совсем ощущения что я чего-то толковое делаю((( как разбавить эти однотипные задачи интересной разработкой или чем-нить еще?

2023-05-01 21:59 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет

2023-05-01 22:00 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/ewm/controller/pub/EventPublicController.java
> +    private final DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Привет, думаю дело в том что тут учебные задачи и они по сути уже однотипны, тут ничего не поделать - просто идет набивка руки

в реальности в продавшене интереснее обычно

2023-05-02 02:38 UTC, merged